import localFont from "next/font/local";
import '../styles/globals.css'
import Header from "./_components/Header";
import Footer from "./_components/footer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: {
    template:"%s | the wild oasis",
    default:"welcome to the wild oasis"
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header/>
        <main className="max-w-screen-2xl mx-auto ">{children}</main>
      {/* <Footer/> */}
      </body>
    </html>
  );
}
